const express=require('express');const path=require('path');const fs=require('fs');const bcrypt=require('bcryptjs');const jwt=require('jsonwebtoken');const ExcelJS=require('exceljs');
const app=express(),PORT=process.env.PORT||3000,JWT_SECRET=process.env.JWT_SECRET||'kiupunu-change-this-secret',DATA=path.join(__dirname,'data','database.json');
app.use(express.json({limit:'3mb'}));app.use(express.static(path.join(__dirname,'public')));
const DEFAULT={school:{name:'SD NEGERI KIUPUNU',address:'Jl. Pelajar',district:'Bikomo Selatan',regency:'Timor Tengah Utara',province:'Nusa Tenggara Timur',headmaster:'',npsn:'',academicYear:'2026/2027',semester:'1'},attendance:{entryTime:'07:30',lateAfter:'08:00'},classes:['I A','I B','II A','II B','III A','III B','IV A','IV B','V A','V B','VI A','VI B']};
function empty(){return {users:[],teachers:[],students:[],attendance:[],settings:JSON.parse(JSON.stringify(DEFAULT)),audit:[]}}
function load(){if(!fs.existsSync(DATA))return empty();let d=JSON.parse(fs.readFileSync(DATA,'utf8'));if(!d||typeof d!=='object')d=empty();d.users=Array.isArray(d.users)?d.users:[];d.teachers=Array.isArray(d.teachers)?d.teachers:[];d.students=Array.isArray(d.students)?d.students:[];d.attendance=Array.isArray(d.attendance)?d.attendance:[];d.audit=Array.isArray(d.audit)?d.audit:[];d.settings={...DEFAULT,...(d.settings||{}),school:{...DEFAULT.school,...(d.settings?.school||{})},attendance:{...DEFAULT.attendance,...(d.settings?.attendance||{})}};return d}
function save(d){fs.mkdirSync(path.dirname(DATA),{recursive:true});fs.writeFileSync(DATA,JSON.stringify(d,null,2))}
function dateNow(){return new Date().toLocaleDateString('en-CA',{timeZone:'Asia/Makassar'})}function timeNow(){return new Date().toLocaleTimeString('id-ID',{timeZone:'Asia/Makassar',hour:'2-digit',minute:'2-digit',second:'2-digit'})}
function audit(d,user,action,detail){d.audit.unshift({id:'log'+Date.now(),date:dateNow(),time:timeNow(),user:user?.username||'-',action,detail});d.audit=d.audit.slice(0,1000)}
function seed(){let d=load();if(!d.users.length){const h=p=>bcrypt.hashSync(p,10);d.users=[{id:'u-admin',username:'admin',passwordHash:h('admin123'),role:'admin',name:'Administrator',active:true},{id:'u-piket',username:'piket',passwordHash:h('piket123'),role:'piket',name:'Guru Piket',active:true},{id:'u-guru',username:'guru',passwordHash:h('guru123'),role:'guru',name:'Guru Kelas',active:true}];d.teachers=[{id:'g1',name:'Siti Aminah, S.Pd',nip:'198501012010012001',email:'',phone:'',faceDescriptor:null},{id:'g2',name:'Budi Santoso, S.Pd',nip:'198603032011011002',email:'',phone:'',faceDescriptor:null},{id:'g3',name:'Rina Lestari, S.Pd',nip:'198706122012022003',email:'',phone:'',faceDescriptor:null}];d.students=[{id:'s1',name:'Andi Pratama',nis:'1001',nisn:'',className:'IV A',gender:'L',faceDescriptor:null},{id:'s2',name:'Bunga Lestari',nis:'1002',nisn:'',className:'IV A',gender:'P',faceDescriptor:null},{id:'s3',name:'Citra Dewi',nis:'1003',nisn:'',className:'IV A',gender:'P',faceDescriptor:null},{id:'s4',name:'Dika Saputra',nis:'1004',nisn:'',className:'IV A',gender:'L',faceDescriptor:null},{id:'s5',name:'Elsa Putri',nis:'1005',nisn:'',className:'IV A',gender:'P',faceDescriptor:null},{id:'s6',name:'Fajar Maulana',nis:'1006',nisn:'',className:'V A',gender:'L',faceDescriptor:null}];save(d)}}seed();
function auth(req,res,next){try{const h=req.headers.authorization||'';if(!h.startsWith('Bearer '))throw 0;req.user=jwt.verify(h.slice(7),JWT_SECRET);next()}catch{res.status(401).json({error:'Sesi tidak valid atau sudah berakhir'})}}function allow(...r){return(req,res,next)=>r.includes(req.user.role)?next():res.status(403).json({error:'Akses ditolak'})}
function arr(d,type){return type==='teacher'?d.teachers:type==='student'?d.students:type==='teachers'?d.teachers:type==='students'?d.students:null}function person(d,type,id){return arr(d,type)?.find(x=>x.id===id)}
function dist(a,b){if(!Array.isArray(a)||!Array.isArray(b)||a.length!==b.length)return 999;let s=0;for(let i=0;i<a.length;i++){const x=a[i]-b[i];s+=x*x}return Math.sqrt(s/a.length)}
app.get('/api/info',(q,s)=>s.json(load().settings.school));
app.post('/api/login',async(req,res)=>{const d=load(),u=d.users.find(x=>x.username===req.body?.username&&x.active!==false);if(!u||!(await bcrypt.compare(req.body?.password||'',u.passwordHash)))return res.status(401).json({error:'Username atau password salah'});const token=jwt.sign({id:u.id,username:u.username,name:u.name,role:u.role},JWT_SECRET,{expiresIn:'12h'});res.json({token,user:{id:u.id,username:u.username,name:u.name,role:u.role}})});
app.get('/api/me',auth,(req,res)=>res.json(req.user));
app.get('/api/settings',auth,(req,res)=>res.json(load().settings));app.put('/api/settings',auth,allow('admin'),(req,res)=>{const d=load();d.settings.school={...d.settings.school,...(req.body.school||{})};d.settings.attendance={...d.settings.attendance,...(req.body.attendance||{})};d.settings.classes=Array.isArray(req.body.classes)?req.body.classes:d.settings.classes;audit(d,req.user,'UBAH PENGATURAN','Pengaturan sekolah/jam absensi diperbarui');save(d);res.json(d.settings)});
app.get('/api/dashboard',auth,(req,res)=>{const d=load(),day=dateNow(),a=d.attendance.filter(x=>x.date===day),tp=a.filter(x=>x.personType==='teacher'),sp=a.filter(x=>x.personType==='student'),present=x=>['Hadir','Terlambat'].includes(x.status);let week=[];for(let i=6;i>=0;i--){const z=new Date();z.setDate(z.getDate()-i);const ds=z.toLocaleDateString('en-CA',{timeZone:'Asia/Makassar'}),x=d.attendance.filter(q=>q.date===ds);week.push({date:ds,teachers:x.filter(q=>q.personType==='teacher'&&present(q)).length,students:x.filter(q=>q.personType==='student'&&present(q)).length})}const allDates=[...new Set(d.attendance.map(x=>x.date))].sort();const allAttendance=allDates.map(ds=>{const x=d.attendance.filter(q=>q.date===ds);return {date:ds,teachers:x.filter(q=>q.personType==='teacher'&&present(q)).length,students:x.filter(q=>q.personType==='student'&&present(q)).length,izin:x.filter(q=>q.status==='Izin').length,sakit:x.filter(q=>q.status==='Sakit').length,alpa:x.filter(q=>q.status==='Alpa').length,total:x.length}});const statusAll={hadir:d.attendance.filter(x=>x.status==='Hadir').length,terlambat:d.attendance.filter(x=>x.status==='Terlambat').length,izin:d.attendance.filter(x=>x.status==='Izin').length,sakit:d.attendance.filter(x=>x.status==='Sakit').length,alpa:d.attendance.filter(x=>x.status==='Alpa').length};res.json({date:day,totalTeachers:d.teachers.length,totalStudents:d.students.length,teacherPresent:tp.filter(present).length,studentPresent:sp.filter(present).length,teacherLate:tp.filter(x=>x.status==='Terlambat').length,studentLate:sp.filter(x=>x.status==='Terlambat').length,teacherMissing:Math.max(0,d.teachers.length-tp.length),studentMissing:Math.max(0,d.students.length-sp.length),week,allAttendance,statusAll})});
app.get('/api/people/:type',auth,(req,res)=>{const d=load(),a=arr(d,req.params.type);if(!a)return res.status(404).json({error:'Tipe tidak valid'});res.json(a.map(x=>({...x,faceDescriptor:!!x.faceDescriptor})))});
app.post('/api/people/:type',auth,allow('admin'),(req,res)=>{const d=load(),t=req.params.type;if(t==='teachers'){const p={id:'g'+Date.now(),name:String(req.body.name||'').trim(),nip:req.body.nip||'',email:req.body.email||'',phone:req.body.phone||'',faceDescriptor:null};if(!p.name)return res.status(400).json({error:'Nama wajib diisi'});d.teachers.push(p);audit(d,req.user,'TAMBAH GURU',p.name);save(d);return res.json(p)}if(t==='students'){const p={id:'s'+Date.now(),name:String(req.body.name||'').trim(),nis:req.body.nis||'',nisn:req.body.nisn||'',className:req.body.className||d.settings.classes[0],gender:req.body.gender||'',faceDescriptor:null};if(!p.name)return res.status(400).json({error:'Nama wajib diisi'});d.students.push(p);audit(d,req.user,'TAMBAH SISWA',p.name);save(d);return res.json(p)}res.status(400).json({error:'Tipe tidak valid'})});
app.put('/api/people/:type/:id',auth,allow('admin'),(req,res)=>{const d=load(),p=person(d,req.params.type,req.params.id);if(!p)return res.status(404).json({error:'Data tidak ditemukan'});const face=p.faceDescriptor;const fields=req.params.type==='teachers'?['name','nip','email','phone']:['name','nis','nisn','className','gender'];fields.forEach(k=>{if(req.body[k]!==undefined)p[k]=req.body[k]});p.faceDescriptor=face;audit(d,req.user,'UBAH DATA',p.name);save(d);res.json({...p,faceDescriptor:!!p.faceDescriptor})});
app.delete('/api/people/:type/:id',auth,allow('admin'),(req,res)=>{const d=load(),key=req.params.type==='teachers'?'teachers':'students',p=d[key].find(x=>x.id===req.params.id);if(!p)return res.status(404).json({error:'Data tidak ditemukan'});d[key]=d[key].filter(x=>x.id!==req.params.id);d.attendance=d.attendance.filter(x=>x.personId!==req.params.id);audit(d,req.user,'HAPUS DATA',p.name);save(d);res.json({ok:true})});
app.post('/api/face/enroll',auth,allow('admin'),(req,res)=>{const d=load(),p=person(d,req.body.type,req.body.id);if(!p)return res.status(404).json({error:'Data tidak ditemukan'});if(!Array.isArray(req.body.descriptor)||req.body.descriptor.length!==128)return res.status(400).json({error:'Descriptor wajah tidak valid'});p.faceDescriptor=req.body.descriptor;audit(d,req.user,'DAFTAR WAJAH',p.name);save(d);res.json({ok:true})});
app.post('/api/face/verify',auth,allow('piket','guru','admin'),(req,res)=>{const d=load(),a=arr(d,req.body.type),desc=req.body.descriptor;if(!Array.isArray(desc)||desc.length!==128)return res.status(400).json({error:'Descriptor tidak valid'});let best=null,bd=999;for(const p of a||[]){if(p.faceDescriptor){const x=dist(desc,p.faceDescriptor);if(x<bd){bd=x;best=p}}}const threshold=Number(process.env.FACE_THRESHOLD||.52);if(!best||bd>threshold)return res.status(404).json({matched:false,error:'Wajah belum dikenali.'});const day=dateNow(),old=d.attendance.find(x=>x.personId===best.id&&x.date===day);if(old)return res.json({matched:true,already:true,person:{id:best.id,name:best.name,className:best.className||''},record:old,distance:bd});const [hh,mm]=timeNow().split(':').map(Number),[lh,lm]=d.settings.attendance.lateAfter.split(':').map(Number),late=hh*60+mm>=lh*60+lm;const r={id:'a'+Date.now(),personId:best.id,personType:req.body.type,name:best.name,className:best.className||'',date:day,time:timeNow(),status:late?'Terlambat':'Hadir',method:'Kamera + Verifikasi Wajah',note:''};d.attendance.push(r);audit(d,req.user,'ABSEN KAMERA',best.name+' - '+r.status);save(d);res.json({matched:true,already:false,person:{id:best.id,name:best.name,className:best.className||''},record:r,distance:bd})});
app.get('/api/attendance',auth,(req,res)=>{const d=load();let a=[...d.attendance];const {from,to,type,className,status,date,search}=req.query;if(date)a=a.filter(x=>x.date===date);if(from)a=a.filter(x=>x.date>=from);if(to)a=a.filter(x=>x.date<=to);if(type)a=a.filter(x=>x.personType===type);if(className)a=a.filter(x=>x.className===className);if(status)a=a.filter(x=>x.status===status);if(search){const q=search.toLowerCase();a=a.filter(x=>x.name.toLowerCase().includes(q))}if(req.user.role==='guru')a=a.filter(x=>x.personType==='student');a.sort((x,y)=>(y.date+y.time).localeCompare(x.date+x.time));res.json(a)});
app.post('/api/attendance/manual',auth,allow('admin','guru','piket'),(req,res)=>{const d=load(),p=person(d,req.body.personType,req.body.personId);if(!p)return res.status(404).json({error:'Data tidak ditemukan'});const day=req.body.date||dateNow(),old=d.attendance.find(x=>x.personId===p.id&&x.date===day);if(old){old.status=req.body.status||old.status;old.note=req.body.note||'';old.method='Manual';audit(d,req.user,'UBAH ABSENSI',p.name+' - '+old.status);save(d);return res.json(old)}const r={id:'a'+Date.now(),personId:p.id,personType:req.body.personType,name:p.name,className:p.className||'',date:day,time:timeNow(),status:req.body.status||'Hadir',method:'Manual',note:req.body.note||''};d.attendance.push(r);audit(d,req.user,'ABSEN MANUAL',p.name+' - '+r.status);save(d);res.json(r)});
app.put('/api/attendance/:id',auth,allow('admin'),(req,res)=>{const d=load(),r=d.attendance.find(x=>x.id===req.params.id);if(!r)return res.status(404).json({error:'Tidak ditemukan'});['status','note','date','time'].forEach(k=>{if(req.body[k]!==undefined)r[k]=req.body[k]});audit(d,req.user,'EDIT ABSENSI',r.name+' - '+r.status);save(d);res.json(r)});app.delete('/api/attendance/:id',auth,allow('admin'),(req,res)=>{const d=load(),r=d.attendance.find(x=>x.id===req.params.id);d.attendance=d.attendance.filter(x=>x.id!==req.params.id);if(r)audit(d,req.user,'HAPUS ABSENSI',r.name);save(d);res.json({ok:true})});
app.get('/api/summary',auth,(req,res)=>{const d=load();let a=d.attendance;const {from,to,type,className}=req.query;if(from)a=a.filter(x=>x.date>=from);if(to)a=a.filter(x=>x.date<=to);if(type)a=a.filter(x=>x.personType===type);if(className)a=a.filter(x=>x.className===className);const map={};for(const x of a){const k=x.personId;if(!map[k])map[k]={personId:k,name:x.name,className:x.className,hadir:0,terlambat:0,izin:0,sakit:0,alpa:0,total:0};map[k][({Hadir:'hadir',Terlambat:'terlambat',Izin:'izin',Sakit:'sakit',Alpa:'alpa'}[x.status]||'hadir')]++;map[k].total++}res.json(Object.values(map))});
app.get('/api/audit',auth,allow('admin'),(req,res)=>res.json(load().audit));
app.get('/api/users',auth,allow('admin'),(req,res)=>res.json(load().users.map(x=>({id:x.id,username:x.username,name:x.name,role:x.role,active:x.active!==false}))));
app.post('/api/users',auth,allow('admin'),(req,res)=>{const d=load(),{username,password,name,role}=req.body;if(!username||!password||!name||!['admin','piket','guru'].includes(role))return res.status(400).json({error:'Data pengguna belum lengkap'});if(d.users.some(x=>x.username===username))return res.status(400).json({error:'Username sudah digunakan'});const u={id:'u'+Date.now(),username,name,role,active:true,passwordHash:bcrypt.hashSync(password,10)};d.users.push(u);audit(d,req.user,'TAMBAH PENGGUNA',username);save(d);res.json({id:u.id,username:u.username,name:u.name,role:u.role,active:true})});
app.put('/api/users/:id',auth,allow('admin'),(req,res)=>{const d=load(),u=d.users.find(x=>x.id===req.params.id);if(!u)return res.status(404).json({error:'Pengguna tidak ditemukan'});if(req.body.name!==undefined)u.name=req.body.name;if(req.body.role&&['admin','piket','guru'].includes(req.body.role))u.role=req.body.role;if(req.body.active!==undefined)u.active=!!req.body.active;if(req.body.password)u.passwordHash=bcrypt.hashSync(req.body.password,10);audit(d,req.user,'UBAH PENGGUNA',u.username);save(d);res.json({id:u.id,username:u.username,name:u.name,role:u.role,active:u.active})});
app.get('/api/export',auth,async(req,res)=>{const d=load();let a=d.attendance;if(req.query.from)a=a.filter(x=>x.date>=req.query.from);if(req.query.to)a=a.filter(x=>x.date<=req.query.to);if(req.query.type)a=a.filter(x=>x.personType===req.query.type);if(req.query.className)a=a.filter(x=>x.className===req.query.className);const wb=new ExcelJS.Workbook(),ws=wb.addWorksheet('Rekap Absensi');ws.addRow([d.settings.school.name]);ws.addRow(['REKAP ABSENSI']);ws.addRow([`Periode ${req.query.from||'-'} s.d. ${req.query.to||'-'}`]);ws.addRow([]);ws.addRow(['No','Tanggal','Waktu','Nama','Jenis','Kelas','Status','Metode','Keterangan']);a.forEach((x,i)=>ws.addRow([i+1,x.date,x.time,x.name,x.personType==='student'?'Siswa':'Guru',x.className||'',x.status,x.method,x.note||'']));ws.columns.forEach(c=>c.width=18);ws.getRow(1).font={bold:true,size:14};res.setHeader('Content-Type','application/vnd.openxmlformats-officedocument.spreadsheetml.sheet');res.setHeader('Content-Disposition','attachment; filename="Rekap_Absensi_SD_Negeri_Kiupunu.xlsx"');await wb.xlsx.write(res);res.end()});
app.get('*',(req,res)=>res.sendFile(path.join(__dirname,'public','index.html')));app.listen(PORT,()=>console.log(`Absensi Kiupunu V3 berjalan di port ${PORT}`));
